### ISSUE TITLE
XSS fixes

### ISSUE THREAD

**Issue by Thynix** [alexbeletsky/github-commits-widget#13]
We've done some work on the widget to encode data from the JSON to avoid XSS. Sadly we didn't break up enough of the work to make it easy to open a pull request. Would you like to incorporate these changes somehow? [link](https://github.com/freenet/website-staging/blob/master/js/github-commits-widget/github.commits.widget-1.js)

Changes include:
- XSS mitigation though jQuery's encoding functions.
- Removing the rendered link back to this repository, and adding one in the source.
- Adding the license to the source.

**Comment by alexbeletsky** [comment]
Please, do not hesitate and make a pull request, it will be much easier to see the diff and make conclusions based on it ;)

**Comment by Thynix** [comment]
[Opened](https://github.com/alexanderbeletsky/github-commits-widget/pull/14).

**Comment by alexbeletsky** [comment]
Merged, thx for contribution!
