### ISSUE TITLE
404 on demo

### ISSUE THREAD

**Issue by paulirish** [alexbeletsky/github-commits-widget#7]
I think maybe v2 was deprecated?

The demo fails looking for https://github.com/api/v2/json/commits/list/alexanderbeletsky/github.commits.widget/master?callback=gh.__jsonp_callbacks%5B1340230142995%5D

**Comment by alexbeletsky** [comment]
@paulirish Thank you for registering that,

It used to work fine on v2 last time I checked it. Anyway, it's good time to update it to v3 ;)

**Comment by alexbeletsky** [comment]
Confirmed, will fix it soon.

**Comment by bitsteller** [comment]
I have already made a little fork that works with the api v3: https://github.com/bitsteller/github.commits.widget. Maybe that can help you.

**Comment by alexbeletsky** [comment]
@bitsteller It looks the similar to something I with to do.. Please do a pull request :)

**Comment by alexbeletsky** [comment]
Fixed by pull request from @bitsteller
